### ISSUE TITLE
Timestamp.__mul__ & __div__ should keep account of unit conversions

### ISSUE THREAD

**Issue by adriaanph** [ska-sa/katpoint#60]
`Timestamp.__mul__` & `.__div__` & `.__truediv__` necessarily imply change of units, however these unit conversions are currently not tracked at all, which makes it very easy for users to abuse.

Possible suggestions:
1) let `__mul__`, `__div__` & `__truediv__` enforce the use of the `numericalunits` (or equivalent) module. in doing this ensure that `Timestamp.secs` always represents the value in seconds

2) alternatively add instance variables for the typical units, e.g. `Timestamp.millisec`

**Comment by ludwigschwardt** [comment]
The plan is to base katpoint on Astropy by the middle of the year, so then we get all the unit-y goodness for free.

The idea behind these methods was never to convert between seconds and milliseconds / MJD / etc but rather to tweak the time scale (i.e. ts *= 1.001) or use a different `scale_factor_timestamp` for workarounds.

I'm happy to keep it as is and expect users of these methods to know what they are doing :-)
