### ISSUE TITLE
 Deprecation Warning and AttributeError in katpoint Library

### ISSUE THREAD

**Issue by tmaretela** [ska-sa/katpoint#80]
Hello,

I hope this message finds you well. I'm currently using the katpoint library for a project involving optical pointing, and I've encountered a compatibility issue that seems to stem from the use of deprecated numpy types in the library. I would like to bring this issue to your attention and seek guidance on how to address it.

When using the library in combination with the latest versions of numpy, specifically those versions that have deprecated np.bool, I encounter both a Deprecation Warning and an AttributeError in certain parts of my code. This issue seems to be originating from within the katpoint library, particularly in areas where numpy types are used.

The Deprecation Warning message reads:

FutureWarning: Pointing model parameters that are not being fitted will be kept in future and not zeroed - zero the model beforehand instead
  warnings.warn('Pointing model parameters that are not being fitted will be kept in ...

The AttributeError message reads:

AttributeError: module 'numpy' has no attribute 'bool'.
'np.bool' was a deprecated alias for the builtin 'bool'. To avoid this error in existing code, use 'bool' by itself.

I understand that the issue might be related to the deprecated numpy types used within the library. I wanted to bring this to your attention and inquire about any plans to address this issue in an upcoming release. It's causing conflicts when using the library in conjunction with modern versions of numpy.

Could you kindly provide guidance on any immediate workarounds or potential solutions? If a fix is planned in the near future, I'll be happy to wait for the updated release.

Thank you for your attention to this matter. I appreciate your work on maintaining the katpoint library and look forward to your response.

Best regards
Thabang Maretela
tmaretela@sarao.ac.za

**Comment by ludwigschwardt** [comment]
Thanks, Thabang!

I'll fix this in a mini-release shortly.

In the meantime you can use `pip install numpy<1.24` to use an older version of NumPy. That fixes the `AttributeError`.

The `FutureWarning` can be removed by calling `model.set()` before `model.fit()` and also adding `keep_disabled_params=True` to that function.
